# -*- coding: utf-8 -*-
"""pytesseract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uUXfdlxqpX1POHK0F-G5dA8K4fB7rWxe
"""

import random
import os
import shutil
import pytesseract
import cv2
try:
    from PIL import Image
except ImportError:
    import Image

image_path = "targetDoc.jpg"

img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow('Result', img)

extractedInformation = pytesseract.image_to_string(Image.open(image_path))
print(extractedInformation)
