version: '3.3'

services:
  postgres:
    container_name: postgres_container
    build: ./postgres_docker
    ports:
      - "5432:5432"
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgres/data
volumes:
  postgres-data: